openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest times component"
  description: "Rest API for the user component of spica communication server"
servers:
  - url: http://localhost/api

paths:
  /user/refresh:
    get:
      tags:
        - user
      operationId: "refreshUsers"
      description: "refreshes all users from external systems"
      responses:
        '200':
          description: 'Null response'

