openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest project component"
  description: "Rest API for the time component of spica communication server"
servers:
  - url: http://localhost/api

paths:
  /projects:
    get:
      tags:
        - project
      operationId: "getProjects"
      description: "returns all projects the current user is authorized to see"
      responses:
        '200':
          description: list of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectContainerInfo"
    post:
      tags:
        - project
      operationId: "createProject"
      description: "creates a new project"
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: created project
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectInfo"

  /projects/{projectId}/topics:
    get:
      tags:
        - topic
      operationId: "getTopics"
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: list of topics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicContainerInfo"

    post:
      tags:
        - topic
      operationId: "createTopic"
      description: "creates a new topic"
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: created topic
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicInfo"

  /topics/import/{userId}:
    post:
      tags:
        - topic
      operationId: "importTopics"
      description: "import topics for user from external system (currently only jira)"
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
        - in: query
          name: usernameExternalSystem
          schema:
            type: string
          required: true
        - in: query
          name: passwordExternalSystem
          schema:
            type: string
          required: true
      responses:
        '200':
          description: created topic
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicContainerInfo"

  /topics/{topicId}:
    delete:
      tags:
        - topic
      operationId: "deleteTopic"
      parameters:
        - in: path
          name: topicId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'Null response'


components:
  schemas:
    ProjectInfo:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        parent:
          $ref: "#/components/schemas/ProjectInfo"

    ProjectContainerInfo:
      type: "object"
      properties:
        projects:
          type: "array"
          items:
            $ref: "#/components/schemas/ProjectInfo"


    TopicInfo:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        state:
          type: "string"
        externalSystemKey:
          type: "string"
        externalSystemID:
          type: "string"
        project:
          $ref: "#/components/schemas/ProjectInfo"
        parent:
          $ref: "#/components/schemas/TopicInfo"


    TopicContainerInfo:
      type: "object"
      properties:
        topics:
          type: "array"
          items:
            $ref: "#/components/schemas/TopicInfo"