openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest communication component"
  description: "Rest API for the communication component of spica communication server"
servers:
  - url: http://localhost/api
security:
  - BasicAuth

paths:

  /messagecontainer/{referenceType}/{referenceId}:
    get:
      tags:
        - communication
      operationId: "getMessagecontainer"
      parameters:
      - in: path
        name: referenceType
        schema:
          type: string
        required: true
      - in: path
        name: referenceId
        schema:
          type: string
        required: true
      responses:
          '200':
            description: message container
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MessagecontainerInfo"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    MessageInfo:
      type: "object"
      properties:
        id:
          type: "string"
        message:
          type: "string"
        type:
          $ref: "#/components/schemas/MessageType"
        creatorId:
          type: "string"
        creatorMailadresse:
          type: "string"
        recipientId:
          type: "string"
        recipientMailadresse:
          type: "string"
        creationtime:
          type: "string"
          format: "date-time"
        readtime:
          type: "string"
          format: "date-time"
        sendtime:
          type: "string"
          format: "date-time"
        documents:
          type: "array"
          items:
            type: "string"


    MessagecontainerInfo:
      type: "object"
      properties:
        message:
          type: "array"
          items:
            $ref: "#/components/schemas/MessageInfo"
        topic:
          type: "string"

    MessageType:
      type: string
      enum:
        - phonecall
        - chat
        - mail


