language: java
language: node_js
install: true

node_js:
  - 15

os:
  - linux
  - osx

jdk:
  - openjdk14

script:
  - ./gradlew build check -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
