openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest chat component"
  description: "Rest API for the chat component of spica communication server"
servers:
  - url: http://localhost/api

paths:

  /messagecontainer/{referenceType}/{referenceId}:
    get:
      tags:
        - chat
      operationId: "getMessagecontainer"
      parameters:
      - in: path
        name: referenceType
        schema:
          type: string
        required: true
      - in: path
        name: referenceId
        schema:
          type: string
        required: true
      responses:
          '200':
            description: message container
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MessagecontainerInfo"

components:
  schemas:
    MessageInfo:
      type: "object"
      properties:
        id:
          type: "string"
        message:
          type: "string"
        type:
          type: "string"
        creator:
          type: "string"
        documents:
          type: "array"
          items:
            type: "string"


    MessagecontainerInfo:
      type: "object"
      properties:
        message:
          type: "array"
          items:
            $ref: "#/components/schemas/MessageInfo"




