# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=spica
      - POSTGRES_PASSWORD=spica
      - POSTGRES_DB=spica
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    networks: 
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spica"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - default

  spica:
    image: markusoley/spica:0.15
    container_name: spica
    restart: unless-stopped
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spica
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_USERNAME=spica
      - SPRING_DATASOURCE_PASSWORD=spica
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL10Dialect
    depends_on:
      postgres:
        condition: service_healthy

    ports: 
      - 8765:8765
      
    volumes:
      - ./conf/spica.properties:/app/.spica/spica.properties
    networks: 
      - default

networks: 
  default: 
