version: "3"
services:
  nginx:
    image: nginx:1.15.9
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./log:/var/log/nginx
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.crt:/etc/nginx/nginx.crt
      - ./conf/nginx.key:/etc/nginx/nginx.key

  spica:
    image: markusoley/spica:0.14
    container_name: spica
    restart: unless-stopped
    volumes:
      - ./conf/spica.properties:/app/.spica/spica.properties
