openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest software component"
  description: "Rest API for the software component of spica"
servers:
  - url: http://localhost:8765/api
security:
  - BasicAuth

paths:
  /software/list:
    get:
      tags:
        - software
      operationId: "getSoftware"
      description: "get list of software"
      responses:
        '200':
          description: 'skill'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Software"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Deployment:
      type: "object"
      properties:
       id:
         type: "string"
       location:
         type: "string"

    Status:
      type: "object"
      properties:
        id:
          type: "string"
        additionalText:
          type: "string"

    Type:
      type: "object"
      properties:
        id:
          type: "string"

    TeamMember:
      type: "object"
      properties:
        id:
          type: "string"
        role:
          type: "string"

    SoftwareAggregate:
      type: "object"
      properties:
        software:
          type: array
          items:
            $ref: "#/components/schema/Software"

    Software:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        requirement:
          type: "string"
        teammembers:
          type: array
          items:
            $ref: "#/components/schema/TeamMember"
        typeId:
          $ref: "#/components/schema/Type"
        statusId:
          $ref: "#/components/schema/Status"
        vcs:
          type: "string"
        technologies:
          type: array
          items:
            type: "string"
        parent:
          $ref: "#/components/schema/Software"
        children:
          type: array
          items:
            $ref: "#/components/schema/Software"


