openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest software component"
  description: "Rest API for the software component of spica"
servers:
  - url: http://localhost:8765/api
security:
  - BasicAuth

paths:
  /software/deployments/list:
    get:
      tags:
        - software
      operationId: "getDeployments"
      description: "get list of deployments"
      responses:
        '200':
          description: 'list of valid deployments'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IdAndDisplaynameInfo"

  /software/types/list:
    get:
      tags:
        - software
      operationId: "getTypes"
      description: "get list of types"
      responses:
        '200':
          description: 'list of valid types'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IdAndDisplaynameInfo"

  /software/states/list:
    get:
      tags:
        - software
      operationId: "getStates"
      description: "get list of states"
      responses:
        '200':
          description: 'list of valid states'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IdAndDisplaynameInfo"

  /software/{softwareId}:
    get:
      tags:
        - software
      operationId: "getSoftwareById"
      description: "get software with id"
      parameters:
        - in: path
          name: softwareId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: software
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SoftwareInfo"
  /software/list:
    get:
      tags:
        - software
      operationId: "getSoftware"
      description: "get list of software"
      responses:
        '200':
          description: 'list of software items'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SoftwareInfo"
    post:
      tags:
        - software
      operationId: "setSoftware"
      description: "set list of software"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SoftwareInfo"

      responses:
        '200':
          description: 'Null response'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:

    IdAndDisplaynameInfo:
      type: "object"
      properties:
        id:
          type: "string"
        displayname:
          type: "string"

    TeamMemberInfo:
      type: "object"
      properties:
        user:
          type: "string"
        role:
          type: "string"

    SoftwareInfo:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        requirement:
          type: "string"
        deployment:
           $ref: "#/components/schema/IdAndDisplaynameInfo"
        location:
          type: "string"
        format:
          type: "string"
        type:
          $ref: "#/components/schema/IdAndDisplaynameInfo"
        group:
          type: "string"
        state:
          $ref: "#/components/schema/IdAndDisplaynameInfo"
        active:
          type: "boolean"
        needsAction:
          type: "boolean"
        needsActionDescription:
          type: "string"
        technicalDebt:
          type: "integer"
        complexity:
          type: "integer"
        maintainability:
          type: "integer"


        teammembers:
          type: array
          items:
            $ref: "#/components/schema/TeamMemberInfo"

        vcs:
          type: "string"
        technologies:
          type: array
          items:
            type: "string"
        children:
          type: array
          items:
            $ref: "#/components/schema/SoftwareInfo"

    RelationInfo:
      type: "object"
      properties:
        relationtype:
          type: "string"
        source:
          $ref: "#/components/schema/SoftwareInfo"
        target:
          $ref: "#/components/schema/SoftwareInfo"
