openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest software component"
  description: "Rest API for the software component of spica"
servers:
  - url: http://localhost:8765/api
security:
  - BasicAuth

paths:
  /software/list:
    get:
      tags:
        - software
      operationId: "getSoftware"
      description: "get list of software"
      responses:
        '200':
          description: 'skill'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SoftwareInfo"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    DeploymentInfo:
      type: "object"
      properties:
       id:
         type: "string"
       location:
         type: "string"

    StatusInfo:
      type: "object"
      properties:
        id:
          type: "string"
        additionalText:
          type: "string"

    TypeInfo:
      type: "object"
      properties:
        id:
          type: "string"

    TeamMemberInfo:
      type: "object"
      properties:
        id:
          type: "string"
        role:
          type: "string"


    SoftwareInfo:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        requirement:
          type: "string"
        teammembers:
          type: array
          items:
            $ref: "#/components/schema/TeamMemberInfo"
        type:
          $ref: "#/components/schema/TypeInfo"
        status:
          $ref: "#/components/schema/StatusInfo"
        vcs:
          type: "string"
        technologies:
          type: array
          items:
            type: "string"
        parent:
          $ref: "#/components/schema/SoftwareInfo"
        children:
          type: array
          items:
            $ref: "#/components/schema/SoftwareInfo"


