openapi: "3.0.0"
info:
  version: 1.0.0
  title: "spica rest times component"
  description: "Rest API for the time component of spica communication server"
servers:
  - url: http://localhost:8765/api
security:
  - BasicAuth

paths:
  /events:
    get:
      tags:
        - times
      operationId: "getEvents"
      description: "returns all events of the parameterized day the current user is authorized to see"
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: 'events'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventInfo"

    post:
      tags:
        - times
      operationId: "createEvents"
      description: "creates new events"
      parameters:
        - name: name
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'Null response'


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:

    EventContainerInfo:
      type: "object"
      properties:
        plannedEvents:
          type: "array"
          items:
            $ref: "#/components/schemas/EventInfo"
        realEvents:
          type: "array"
          items:
            $ref: "#/components/schemas/EventInfo"

    EventInfo:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        userId:
          type: "string"
        referenceId:
          type: "string"
        start:
          type: "string"
          format: "date-time"
        stop:
          type: "string"
          format: "date-time"
        eventType:
          $ref: "#/components/schemas/EventType"

    EventType:
      type: string
      enum:
        - task
        - message
        - pause
        - meeting
